# Generated by Django 5.0.1 on 2024-02-27 13:35

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=backend.models.generate_unique_code, max_length=10, unique=True),
        ),
    ]
